def map_patch(name):
    """
        Содержит в себе и возвращает куски, вставлемые генератором в игровую карту
    """
    patch_dict = {
                  'river_3x3': [
                                '00bbb00',
                                '0bbbbb0',
                                'bbb~bbb',
                                'bb~~~bb',
                                'bbb~bbb',
                                '0bbbbb0',
                                '00bbb00',
                                ],
                  'river_4x4': [
                                '000bb000',
                                '00bbbb00',
                                '0bb~~bb0',
                                'bb~~~~bb',
                                'bb~~~~bb',
                                '0bb~~bb0',
                                '00bbbb00',
                                '000bb000',
                                ],
                  'river_5x5': [
                                '000bbb000',
                                '00bbbbb00',
                                '0bb~~~bb0',
                                'bb~~~~~bb',
                                'bb~~~~~bb',
                                'bb~~~~~bb',
                                '0bb~~~bb0',
                                '00bbbbb00',
                                '000bbb000',
                                ],
                  'river_6x6': [
                                '000bbbb000',
                                '00bbbbbb00',
                                '0bb~~~~bb0',
                                'bb~~~~~~bb',
                                'bb~~~~~~bb',
                                'bb~~~~~~bb',
                                'bb~~~~~~bb',
                                '0bb~~~~bb0',
                                '00bbbbbb00',
				'000bbbb000',
                                ],
                  'river_7x7': [
                                '0000bbb0000',
                                '000bbbbb000',
                                '00bb~~~bb00',
                                '0bb~~~~~bb0',
                                'bb~~~~~~~bb',
                                'bb~~~~~~~bb',
                                'bb~~~~~~~bb',
                                '0bb~~~~~bb0',
                                '00bb~~~bb00',
				'000bbbbb000',
				'0000bbb0000',
                                ],
                  'river_8x8': [
                                '0000bbbb0000',
                                '000bbbbbb000',
                                '00bb~~~~bb00',
                                '0bb~~~~~~bb0',
                                'bb~~~~~~~~bb',
                                'bb~~~~~~~~bb',
                                'bb~~~~~~~~bb',
                                'bb~~~~~~~~bb',
                                '0bb~~~~~~bb0',
				'00bb~~~~bb00',
				'000bbbbbb000',
				'0000bbbb0000',
                                ],
                  'river_9x9': [
                                '0000bbbbb0000',
                                '000bbbbbbb000',
                                '00bb~~~~~bb00',
                                '0bb~~~~~~~bb0',
                                'bb~~~~~~~~~bb',
                                'bb~~~~~~~~~bb',
                                'bb~~~~~~~~~bb',
                                'bb~~~~~~~~~bb',
                                'bb~~~~~~~~~bb',
				'0bb~~~~~~~bb0',
				'00bb~~~~~bb00',
				'000bbbbbbb000',
				'0000bbbbb0000',
                                ],
                  'ford_river_5x5': [
                                '00f00',
                                '0fff0',
                                'fffff',
                                '0fff0',
                                '00f00',
                                ]
                  }
    ford_river_dict = {
                  'river_3x3': [
                                '00bbb00',
                                '0bbbbb0',
                                'bbbfbbb',
                                'bbfffbb',
                                'bbbfbbb',
                                '0bbbbb0',
                                '00bbb00',
                                ],
                  'river_4x4': [
                                '000bb000',
                                '00bbbb00',
                                '0bbffbb0',
                                'bbffffbb',
                                'bbffffbb',
                                '0bbffbb0',
                                '00bbbb00',
                                '000bb000',
                                ],
                  'river_5x5': [
                                '000bbb000',
                                '00bbbbb00',
                                '0bbfffbb0',
                                'bbfffffbb',
                                'bbfffffbb',
                                'bbfffffbb',
                                '0bbfffbb0',
                                '00bbbbb00',
                                '000bbb000',
                                ],
                  'river_6x6': [
                                '000bbbb000',
                                '00bbbbbb00',
                                '0bbffffbb0',
                                'bbffffffbb',
                                'bbffffffbb',
                                'bbffffffbb',
                                'bbffffffbb',
                                '0bbffffbb0',
                                '00bbbbbb00',
				'000bbbb000',
                                ],
                  'river_7x7': [
                                '0000bbb0000',
                                '000bbbbb000',
                                '00bbfffbb00',
                                '0bbfffffbb0',
                                'bbfffffffbb',
                                'bbfffffffbb',
                                'bbfffffffbb',
                                '0bbfffffbb0',
                                '00bbfffbb00',
				'000bbbbb000',
				'0000bbb0000',
                                ],
                  'river_8x8': [
                                '0000bbbb0000',
                                '000bbbbbb000',
                                '00bbffffbb00',
                                '0bbffffffbb0',
                                'bbffffffffbb',
                                'bbffffffffbb',
                                'bbffffffffbb',
                                'bbffffffffbb',
                                '0bbffffffbb0',
				'00bbffffbb00',
				'000bbbbbb000',
				'0000bbbb0000',
                                ],
                  'river_9x9': [
                                '0000bbbbb0000',
                                '000bbbbbbb000',
                                '00bbfffffbb00',
                                '0bbfffffffbb0',
                                'bbfffffffffbb',
                                'bbfffffffffbb',
                                'bbfffffffffbb',
                                'bbfffffffffbb',
                                'bbfffffffffbb',
				'0bbfffffffbb0',
				'00bbfffffbb00',
				'000bbbbbbb000',
				'0000bbbbb0000',
                                ],
                  }

    if name in patch_dict:
        return patch_dict[name]
    else:
        return ['zzz', 'zzz', 'zzz',]

